{{- if .Values.cpKafkaRestProxy.enabled -}}
{{- if .Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.cp-kafka-rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "autoscaling.cp-kafka-rest.fullname" . }}
  minReplicas: {{ .Values.cpKafkaRestProxy.minReplicas }}
  maxReplicas: {{ .Values.cpKafkaRestProxy.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: kafka_rest_heap_utilization_pcnt
      target:
        type: AverageValue
        averageValue: {{ .Values.cpKafkaRestProxy.memory.targetPCNT | quote }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: {{ .Values.cpKafkaRestProxy.cpu.targetAverageValue | quote }}
{{- else }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.cp-kafka-rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "autoscaling.cp-kafka-rest.fullname" . }}
  minReplicas: {{ .Values.cpKafkaRestProxy.minReplicas }}
  maxReplicas: {{ .Values.cpKafkaRestProxy.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: kafka_rest_heap_utilization_pcnt
      targetAverageValue: {{ .Values.cpKafkaRestProxy.memory.targetPCNT | quote }}
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ .Values.cpKafkaRestProxy.cpu.targetAverageValue | quote }}
{{- end -}}
{{- end }}