{{- if .Values.esKafkaConnect.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.es-kafka-connect.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "autoscaling.es-kafka-connect.fullname" . }}
  minReplicas: {{ .Values.esKafkaConnect.minReplicas }}
  maxReplicas: {{ .Values.esKafkaConnect.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: {{ .Values.esKafkaConnect.cpu.targetAverageValue | quote }}
  - type: External
    external:
      metric:
        name: kafka_bytesinpersec_oneminuterate
      target:
        type: AverageValue
        averageValue: {{ mul .Values.esKafkaConnect.ingestRateGBPerDayPerPod 11575 }}
{{- end -}}
