{{- if .Values.esKafkaConnect.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.es-kafka-connect.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "autoscaling.es-kafka-connect.fullname" . }}
  minReplicas: {{ .Values.esKafkaConnect.minReplicas }}
  maxReplicas: {{ .Values.esKafkaConnect.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ .Values.esKafkaConnect.cpu.targetAverageValue | quote }}
  - type: External
    external:
      metricName: kafka_bytesinpersec_oneminuterate
      targetAverageValue: {{ mul .Values.esKafkaConnect.ingestRateGBPerDayPerPod 11575 }}
{{- end -}}
