enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: apm-sfapm-python3

podSecurityContext:
  {}

sfapmui:
  image:
    repository: snappyflowml/sfapm-ui
    tag: '3-1-456'
    pullPolicy: IfNotPresent

