enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}

sfapmui:
  image:
    repository: snappyflowml/sfapm-ui
    tag: 'master-3-1-443'
    pullPolicy: IfNotPresent

