---
enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: apm-sfapm-python3
pprof:
  image:
    repository: snappyflowml/pprof-server
    pullPolicy: IfNotPresent
    tag: 'master-0-4-3'
podSecurityContext: {}