apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-sftrace
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: sftrace
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      rum.enabled: true
      jaeger:
        http:
          enabled: true
          host: 0.0.0.0:14268
    queue:
      mem:
        events: 16384
    {{- if .Values.sftrace.output.kafka.enabled }}
    output.kafka:
      enabled: true
      hosts: {{ .Values.sftrace.output.kafka.hosts | toJson }}
      topic: beats
      worker: 1
      channel_buffer_size: 16384
      bulk_max_size: 2048
      compression: "snappy"
    {{- else }}
    output.kafkarest:
      enabled: true
      hosts: ["{{ .Values.sftrace.output.kafkarest.host }}:{{ .Values.sftrace.output.kafkarest.port }}"]
      topic: beats
      token: "{{ .Values.sftrace.output.kafkarest.token }}"
      bulk_max_size: 1024
      worker: 8
    {{- end }}
    setup.template.enabled: false
    logging.metrics.enabled: true
    logging.to_stderr: true
    logging.json: true
    http.enabled: true
    http.host: localhost
    http.port: 5066

