{{- if eq "" .Values.sfapm.cloud }}
{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-jaeger
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: snappyflow-apm
    nginx.ingress.kubernetes.io/rewrite-target: /api/traces/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /jaegertrace
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-jaegersftrace
          servicePort: 14268
{{- end }}
{{- end }}