{{- if eq "azure" .Values.sfapm.cloud }}
{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-jaeger
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    appgw.ingress.kubernetes.io/backend-path-prefix: /api/traces/
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "appGatewaySslCert"
spec:
  rules:
  - http:
      paths:
      - path: /jaegertrace
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-jaegersftrace
            port: 
              number: 14268
        pathType: Exact
{{- end }}
{{- end }}