apiVersion: v2
name: sfapm-python3
description: A Helm chart to deploy snappyflow on Kubernetes
home: https://www.snappyflow.io
type: application
version: 4.0.361
appVersion: 4.0

dependencies:
- name: redis
  version: 0.2.10
  repository: https://snappyflow.github.io/helm-charts/
- name: postgresql
  version: 0.1.5
  repository: https://snappyflow.github.io/helm-charts/
  condition: postgresql.enabled
