{{- if and .Values.global.secrets.aws.enable .Values.global.secrets.aws.use_iam_role }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.secrets.aws.AWS_IAM_ROLE_ARN }}
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
    {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
{{- else if and .Values.global.secrets.gcs.enable .Values.global.secrets.gcs.use_google_service_account }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.global.secrets.gcs.GCP_SERVICE_ACCOUNT_EMAIL }}
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
    {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
{{- else if .Values.global.secrets.azure.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
    {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
{{- end }}
