apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-proxy-blocks
data:
  archival-grpc.conf: |-
    server {
      listen 0.0.0.0:8081 http2;

      location /datasetrawquery.DatasetRawQuery {
        grpc_pass grpc://{{ .Values.archivalReleaseName }}-raw-query-exec-controller:8081;
      }
    }
  datapath-and-archival-rest.conf: |-
    server {
      listen 0.0.0.0:8080;
     
      location /ingest {
        proxy_pass http://{{ .Values.archivalReleaseName }}-ingest-controller/ingest;
      }

      location /logarchival {
        proxy_pass http://{{ .Values.archivalReleaseName }}-log-archival/logarchival;
      }

      location /query {
        proxy_pass http://{{ .Values.archivalReleaseName }}-query-controller/query;
      }

      location /sfkinterface {
        proxy_pass http://{{ .Values.datapathReleaseName }}-sfk-interface/sfkinterface;
      }

      location /profile-quotas {
        proxy_pass http://{{ .Values.datapathReleaseName }}-sfk-interface/profile-quotas;
      }

      location /signatures {
        proxy_pass http://{{ .Values.datapathReleaseName }}-signatures-and-kafka-apis/signatures;
      }

      location //kafka-info {
        proxy_pass http://{{ .Values.datapathReleaseName }}-signatures-and-kafka-apis//kafka-info;
      }
    }
