apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-system-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-system-migraton
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image: snappyflowml/datapath-system-migration:8
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: {{ .Release.Name }}-system-migration-config
            mountPath: "/etc/conf"
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-system-migration-config
          configMap:
            name: {{ .Release.Name }}-system-migration-config
