affinity: {}
containerResources:
  ingestcontroller:
    limits:
      cpu: 50m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi
dataset-controller:
  service:
    servicePort: 5001
external:
  enabled: false
  externalTrafficPolicy: Cluster
  type: NodePort
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/ingest-controller
  tag: '18'
log-archival:
  service:
    servicePort: 5003
minio:
  secrets:
    accessId: gcpminio
    accessKey: gcpminio
nameOverride: ''
nodeSelector: {}
schedulerName: sf-scheduler
schedules:
  sink: '*/5 * * * *'
serverPort: :5000
service:
  servicePort: 5000
spark-manager:
  jobserver:
    service:
      servicePort: 5002
timeBucketSizeMinutes: 15
tolerations: []
