{{- if not .Values.global.subnets }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress-nginx.controller.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "snappyflowcert"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "ingress-nginx.controller.fullname" . }}
            port: 
              number: 80
        pathType: Prefix
{{- end }}
