kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "dataset-raw-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "dataset-raw-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "serverPort": "{{ .Values.serverPort }}",
      "final_segment_size_gb": {{ .Values.appParams.segmentSizeGB }},
      "final_segment_size_buffer_pcnt": {{ .Values.appParams.segmentSizeBufferPCNT }},
      "num_orcs_in_segment": {{ .Values.appParams.numORCInSegment }},
      "num_backtrack_days": {{ .Values.appParams.numBacktrackDaysToDetect }},
      "ingest_controller_url": "http://{{ template "dataset-raw-controller.ingest-controller.fullname" . }}"
    }
