apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "dataset-raw-controller.fullname" . }}
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: apm-saas-datapath
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.global.snappyflowDatapath.releaseName }}-usercreds
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - ok'
    nginx.ingress.kubernetes.io/auth-secret-type: "auth-file"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /datasets-raw-data
        backend:
          service:
            name: {{ template "dataset-raw-controller.fullname" . }} 
            port:
              number: 80
        pathType: Prefix
