apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataset-raw-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "dataset-raw-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}