# Default values for sf-cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  pullPolicy: IfNotPresent
  tag: v1.20.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

overProvisionerResources:
  requests:
    cpu: 2000m
    memory: 8Gi

autoscaler:
  # Specifies whether a autoscaler should be created. Set true in case of AWS
  enabled: true
  nodeUnneededTime: 300s
  serviceAccountName: ""
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi

# Needed in case of eks
eks:
  clusterName: ""
  rolearn: ""
