affinity: {}
containerResources:
  webhook:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 10Mi
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/orc-event-webhook
  tag: '2-0-86'
nameOverride: ''
nodeSelector: {}
schedulerName: sf-scheduler
serverPort: :6003
num_partitions: 3
replication_factor: 2
retention_ms: "86400000"
type": "log"
api_token: "A34DFGGGRTYU"
service:
  servicePort: 6003
tolerations: []
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # Below values are based on requests.
  # Hence value > 100 needs to be calculated based on set limits
  # Below values are calculated such that (limit / request) * 80 -> for 80% target utilization
  targetCPUUtilizationPercentage: 400
  targetMemoryUtilizationPercentage: 400