apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sf-node-manager.fullname" . }}
  labels:
    {{- include "sf-node-manager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sf-node-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sf-node-manager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.global.sfNodeManager.enabled -}}
      priorityClassName: {{ .Values.global.sfNodeManager.priorityClassName }}
      {{- end }}
      schedulerName: {{ .Values.schedulerName }}
      containers:
        - name: nodemanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/bash", "-c"]
          args: ["./manager;"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName 
