{{- if .Values.sfagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-sfagent-plugin-configmap
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    metrics:
      plugins:
      - name: kube-sfagent-nginx
        enabled: true
        interval: 300
        config:
          location: status
          port: 80
          secure: false
    logging:
      plugins:
      - name: nginx-access
        enabled: true
        config:
          log_path: "/var/log/nginx/access-custom.log"
          geo_info: true
          ua_parser: true
          url_normalizer: true
      - name: nginx-error
        enabled: true
        config:
          log_path: "/var/log/nginx/access-custom.log, /var/log/nginx/error.log"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-sfagent-normalization-nginx
data:
  config.yaml: |+
    ---
    interval: 600
    dynamic_rule_generation:
      enabled: false #Rely on normalization algorithm for rule generation.
      rules_length_limit: 10000 #set the value to -1  for specifying no limit
      log_volume: 100000 #set the value to -1  for specifying no limit
    rules:
    - /sfkinterface/*
    - /sfkinterface/*/project/*
    - /sfkinterface/*/project/*/app/*/documentblocks
    - /query/jobs/dummy
    - /query/jobs/*
{{- end }}