{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-kafka.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-prometheus.yml: |+
    startDelaySeconds: 120
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
    - kafka.controller:*
    - kafka.server:*
    - java.lang:*
    - java.nio:*
    - kafka.network:*
    - kafka.log:*
    - kafka.cluster:*
    rules:
    - pattern: kafka.controller<type=(ControllerChannelManager), name=(QueueSize), broker-id=(\d+)><>(Value)
      name: kafka_controller_$1_$2_$4
      labels:
        broker_id: "$3"
    - pattern: kafka.controller<type=(ControllerChannelManager), name=(TotalQueueSize)><>(Value)
      name: kafka_controller_$1_$2_$3
    - pattern: kafka.controller<type=(KafkaController), name=(.+)><>(Value)
      name: kafka_controller_$1_$2_$3
    - pattern: kafka.controller<type=(ControllerStats), name=(.+)><>(Count|OneMinuteRate|FiveMinuteRate)
      name: kafka_controller_$1_$2_$3
    - pattern: kafka.server<type=(ReplicaFetcherManager), name=(.+), clientId=(.+)><>(Value)
      name: kafka_server_$1_$2_$4
      labels:
        client_id: "$3"
    - pattern: kafka.server<type=([^,]+), name=([^,]+), topic=([^,]+), partition=([^,]+)><>(Count|OneMinuteRate|MeanRate|FifteenMinuteRate|FiveMinuteRate)
      name: kafka_server_$1_$2_$5
      labels:
        topic: $3
        partition: $4
        topic_partition: $3_$4
    - pattern: kafka.server<type=([^,]+), name=([^,]+), topic=([^,]+)><>(Count|OneMinuteRate|MeanRate|FifteenMinuteRate|FiveMinuteRate)
      name: kafka_server_$1_$2_$4
      labels:
        topic: $3
    - pattern: kafka.server<type=([^,]+), name=([^,]+), fetcherType=([^,]+)><>(Count|OneMinuteRate|MeanRate|FifteenMinuteRate|FiveMinuteRate)
      name: kafka_server_$1_$2_$4
      labels:
        fetcherType: $3
    - pattern: kafka.server<type=([^,]+), name=([^,]+)><>(Count|OneMinuteRate|MeanRate|FifteenMinuteRate|FiveMinuteRate|Value)
      name: kafka_server_$1_total_$2_$3
    - pattern: kafka.server<type=([^,]+), user=([^,]+), client-id=([^,]+)><>(throttle-time|byte-rate|request-time)
      name: kafka_server_$1_$4
      labels:
        user: $2
        client-id: $3
        client-id_user: $3_$2
    - pattern: kafka.server<type=([^,]+), client-id=([^,]+)><>(throttle-time|byte-rate|request-time)
      name: kafka_server_$1_$3
      labels:
        user: "none"
        client-id: $2
        client-id_user: $2_none
    - pattern: kafka.server<type=([^,]+), user=([^,]+)><>(throttle-time|byte-rate|request-time)
      name: kafka_server_$1_$3
      labels:
        user: $2
        client-id: "none"
        client-id_user: none_$2
    - pattern: kafka.server<type=(.+)><>(queue-size)
      name: kafka_server_$1_$2
    - pattern: kafka.server<type=(DelayedOperationPurgatory), name=(.+), delayedOperation=(.+)><>(Value)
      name: kafka_server_$1_$2_$3_$4
    - pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
      name: kafka_network_$1_$2_$4
      labels:
        network_processor: $3
    - pattern : kafka.network<type=(RequestMetrics), name=(.+), request=([^,]+).*><>(Count|OneMinuteRate|Mean|FiveMinuteRate)
      name: kafka_network_$1_$2_$4
      labels:
        request: $3
    - pattern: kafka.cluster<type=([^,]+), name=([^,]+), topic=([^,]+), partition=([^,]+)><>Value
      name: kafka_cluster_$1_$2
      labels:
        topic: $3
        partition: $4
    - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
      name: kafka_log_$1_$2
      labels:
        topic: $3
        partition: $4
        topic_partition: $3_$4
    - pattern: kafka.log<type=(.+), name=(.+)><>Value
      name: kafka_log_$1_$2
    - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
      name: java_lang_$1_$4_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><(.+)>(\w+)
      name: java_lang_$2_$4_$3_$1
      cache: true
    - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
      name: java_lang_$1_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><>(\w+)
      name: java_lang_$2_$3_$1
      cache: true
    - pattern: java.lang<type=(.*)>
      cache: true
    - pattern: java.nio<type=(.+), name=(.+)><>(\w+)
      name: java_nio_$1_$3_$2
      cache: true
{{- end }}