{{- if .Values.overProvisioning.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-cluster-autoscaler.fullname" . }}-overprovisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sf-cluster-autoscaler.name" . }}-overprovisioner
  template:
    metadata:
      labels:
        app: {{ include "sf-cluster-autoscaler.name" . }}-overprovisioner
    spec:
      schedulerName: {{ .Values.schedulerName }}
      containers:
      - name: overprovisioner
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.overProvisionerResources | nindent 12 }}
      priorityClassName: overprovisioner
{{- end }}