enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: apm-sfapm-python3

image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/sftrace-server
  tag: 'latest'

podSecurityContext:
  {}