apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sf-presto.fullname" . }}-configmap
  labels:
    app: {{ include "sf-presto.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  hive.properties: |+ 
    connector.name = hive-hadoop2
    {{- if .Values.aws.enabled }}
    hive.metastore.uri = thrift://NODE_IP:NODE_PORT
    hive.s3.use-instance-credentials = true
    hive.non-managed-table-writes-enabled = true
    hive.s3select-pushdown.enabled = true
    hive.s3.use-instance-credentials = true
    hive.time-zone = UTC
    hive.metastore-timeout=60s
    {{- else if .Values.azure.enabled }}
    # HDFS
    hive.config.resources=/home/presto-server-0.277/etc/azure-site.xml
    # Metastore
    hive.metastore.uri=thrift://NODE_IP:NODE_PORT
    hive.non-managed-table-writes-enabled=true
    hive.time-zone=UTC
    hive.metastore-timeout=60s
    # Permissions
    hive.allow-drop-table=true
    {{- end }}
