apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-presto.fullname" . }}-worker
  labels:
    app: {{ include "sf-presto.name" . }}-worker
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    snappyflow/component: snappyflow-presto
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sf-presto.name" . }}-worker
      role: sfpresto-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "sf-presto.name" . }}-worker
        release: {{ .Release.Name }}
        role: sfpresto-worker
        snappyflow/component: snappyflow-presto
    spec:
      serviceAccountName: sfpresto-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sfpresto-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          command: ["/bin/bash", "-c"]
          args: ["/home/presto-config; ./worker-init.sh; sleep 3650d;"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
        - name: sfpresto-worker-prometheus-exporter
          command: [/go/metrics]
          image: "{{ .Values.image.sidecarrepository }}:{{ .Values.image.tag }}" 
          imagePullPolicy: Always
