USER-SUPPLIED VALUES:
compaction-controller:
  maxSimultaneousRun: 10
global:
  imagePullSecrets:
  - name: snappyflowdockersecret
  kafkaBrokers: kafka-cp-kafka-headless:9092
  postgresql:
    host: postgres-postgresql.apm
    postgresqlDatabase: archival
    postgresqlPassword: maplelabs
    postgresqlUsername: snappyflow
  secrets:
    aws:
      AWS_ACCESS_KEY_ID: ' '
      AWS_IAM_ROLE_ARN: arn:aws:iam::638509944599:role/On-Premise-EKS-Worker-Node-Role
      AWS_QUEUE_ARN: arn:aws:sqs:us-west-2:638509944599:sf-archival-inventory
      AWS_QUEUE_URL: https://sqs.us-west-2.amazonaws.com/638509944599/sf-archival-inventory
      AWS_SECRET_ACCESS_KEY: ' '
      use_iam_role: true
  sfNodeManager:
    enabled: true
    priorityClassName: sf-critical-pod
  sfScheduler:
    enabled: true
    schedulerName: sf-scheduler
  snappyflowAppName: archival
  snappyflowProjectName: apmmanager-opensearch
spark-history-server:
  s3:
    logDirectory: spark-1535925285-hdfs/spark-hs
spark-manager:
  infrastructure:
    EcsFargate:
      cluster: sf-archival-compaction-3104227275
      compactionSecretArn: arn:aws:secretsmanager:us-west-2:638509944599:secret:snappyflow-docker-secret-518300
      enabled: true
      iamRole: arn:aws:iam::638509944599:role/On-Premise-EKS-Worker-Node-Role
      taskSecurityGroup: sg-03ce0b7481f991d78
      taskSubnet: subnet-0e1fd93f461937ca3
  jobserver:
    sparkProperties:
      logDirectory: spark-1535925285-hdfs/spark-hs
