apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archival
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,pre-delete
    helm.sh/hook-weight: "200"
spec:
  destination:
    namespace: public
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/sf-archival
    repoURL: https://github.com/Pradeep-G-ML/helm-charts.git
    targetRevision: master
    helm:
      valueFiles:
       - values.yaml
      values: |-
       compaction-controller:
         maxSimultaneousRun: 10
       global:
         imagePullSecrets:
         - name: snappyflowdockersecret
         kafkaBrokers: kafka-cp-kafka-headless:9092
         postgresql:
           host: postgres-postgresql.apm
           postgresqlDatabase: archival
           postgresqlPassword: maplelabs
           postgresqlUsername: snappyflow
           servicePort: 5432
         secrets:
           aws:
             AWS_ACCESS_KEY_ID: ' '
             AWS_IAM_ROLE_ARN: arn:aws:iam::159750416379:role/stage-portal-setup-EKS-Worker-Node-Role
             AWS_QUEUE_ARN: arn:aws:sqs:us-west-2:159750416379:sf-archival-inventory
             AWS_QUEUE_URL: https://sqs.us-west-2.amazonaws.com/159750416379/sf-archival-inventory
             AWS_SECRET_ACCESS_KEY: ' '
             use_iam_role: true
         snappyflowAppName: archival
         snappyflowProjectName: snappyflow-app
       spark-history-server:
         s3:
           logDirectory: spark-264722184-hdfs/spark-hs
       spark-manager:
         infrastructure:
           EcsFargate:
             cluster: sf-archival-compaction-179421722
             compactionSecretArn: arn:aws:secretsmanager:us-west-2:159750416379:secret:FargateCompactionSecresss-VXamGn
             enabled: true
             iamRole: arn:aws:iam::159750416379:role/stage-portal-setup-EKS-Worker-Node-Role
             taskSecurityGroup: sg-006ee1ae27b9a8fd4
             taskSubnet: subnet-09a6fcdc2b614e300
         jobserver:
           sparkProperties:
             logDirectory: spark-264722184-hdfs/spark-hs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
